### ISSUE TITLE
Enhancement suggestion: Allow repos to support more than one URL

### ISSUE THREAD

**Issue by BrianAllred** [anatol/pacoloco#1]
Like pacman.conf can support more than one `Server` directive, letting the repositories inside `repos` support more than one `url` directive would be nifty.

**Comment by anatol** [comment]
My understanding is that you are looking for a failover logic adding to `pacoloc`. i.e. if file at the first URL is not available then `pacoloco` tries to download the package from the next server. It is a good idea.
