### ISSUE TITLE
Add support for http proxy

### ISSUE THREAD

**Issue by piozylka** [anatol/pacoloco#38]
Hi, my server is behind corporate proxy so when using pacman I have to define env variables which is pretty annoying.
I thought caching proxy will be great solution to this situation.
Installed pacoloco and running but I see that packages aren't downloading.
Is there any solution to work pacoloco with proxy server  or the server must have internet connection ?

**Comment by anatol** [comment]
Allowing to use http proxy to fetch files from repos sounds like a reasonable request.

I just pushed a (completely untested) commit to `wip` branch. With this change you need to add `http_proxy: YOUR_URL` config option to enable http_proxy. Please try it and let me know if it works for you.

**Comment by piozylka** [comment]
Yep, It's working perfectly.
Thank You for such quick reaction and support.
