### ISSUE TITLE
pacoloco fails to start with a valid cache directory

### ISSUE THREAD

**Issue by ArielRosenfeld** [anatol/pacoloco#4]
```Feb 20 12:09:10 nuc6 systemd[1]: Started Pacoloco caching proxy server.
Feb 20 12:09:10 nuc6 pacoloco[3465322]: pacoloco.go:31: Reading config file from /etc/pacoloco.yaml
Feb 20 12:09:10 nuc6 pacoloco[3465322]: config.go:53: directory /srv/samba2/pacoloco does not exist or isn't writable for user pacoloco
Feb 20 12:09:10 nuc6 systemd[1]: pacoloco.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 12:09:10 nuc6 systemd[1]: pacoloco.service: Failed with result 'exit-code'.
```

```12:09:14 [drago5@nuc6 ~]$ ls -la /srv/samba2/pacoloco
total 8
drwxr-xr-x 2 pacoloco  pacoloco  4096 Feb 20 12:01 .
drwxrwx--T 8 shareuser shareuser 4096 Feb 19 16:46 ..
```

**Comment by anatol** [comment]
The parent directories `/srv/` and `/srv/samba2/` need to be readable and listable by user `pacoloco` ( have the bits `r` and `x` set). To fix your problem either make the parent directories readable by everyone `o+rx` or add `pacoloco` to group `shareuser`.

**Comment by ArielRosenfeld** [comment]
i set the location to limit the application scope to that specific directory so it wont have access to other directories

the default of /var/cache/pacoloco also doesnt give access to /var and /var/cache

other applications dont need access to their root directory to work

**Comment by anatol** [comment]
> i set the location to limit the application scope to that specific directory so it wont have access to other directories

It is fine to limit the access. But you need to make sure that `pacoloco` user has access to the directories as well. 

> the default of /var/cache/pacoloco also doesnt give access to /var and /var/cache

Both these directories have `o+rx` bits set:
```
 $ ls -ld /var
drwxr-xr-x 12 root root 4096 Feb 15 09:46 /var
$ ls -ld /var/cache
drwxr-xr-x 11 root root 4096 Feb 20 08:57 /var/cache
```
Note that it means any user can list content of the directory but *does not* mean the user can read content of the files. Files have their own permission sets.

> other applications dont need access to their root directory to work

If other application can get access to ` /srv/samba2/` it means the apps either run as user `shareuser` or as `root`. If you want pacoloco use this directory then you need to set the directory permissions accordingly.
