### ISSUE TITLE
docker retain sqlite-pkg-cache.db between upgrades

### ISSUE THREAD

**Issue by gary094** [anatol/pacoloco#42]
I learned this the hard way but it seems the `sqlite-pkg-cache.db`  which is responsible to keep track of prefetching is not mapped to a directory outside the container when using docker.

This means whenever you build a new container this file will be created from scratch and is therefore empty.

I would change the docker run command in the README.md:

` docker run -p 9129:9129 -v /path/to/config/pacoloco.yaml:/etc/pacoloco.yaml -v /path/to/cache:/var/cache/pacoloco/pkgs -v /path/to/sqlite-db:/var/cache/pacoloco/sqlite-pkg-cache.db pacoloco` 

I would also be happy to provide my simple docker-compose.yml if you so desire.

**Comment by anatol** [comment]
cc @ilyazzz @Focshole 

Would it be better to put the configuration option to `Dockerfile` directly and avoid the extra configuration done by a user every time?

**Comment by gary094** [comment]
No since any mounting commands are not available in the `Dockerfile`. It wouldn't make any sense either since people do have different directory structures, systems, etc. So mounting volumes and directories actually needs to happen after the image was built.

However I am more than happy to share my docker-compose.yml to easily bring the project up:

`
---
version: "3.8"
services:
  pacoloco:
    container_name: pacoloco
    build: https://github.com/anatol/pacoloco.git
    ports:
      - "9129:9129"
    volumes:
      - /path/to/cache:/var/cache/pacoloco/pkgs
      - /path/to/config/pacoloco.yaml:/etc/pacoloco.yaml
      - /path/to/sqlite-db:/var/cache/pacoloco/sqlite-pkg-cache.db
    networks:
      - pacoloco

networks:
  pacoloco:
    external: true
`


This way users would be able to run `docker-compose up -d` and the application would start

**Comment by anatol** [comment]
Got it.

I am happy with any option that makes Docker management easier. @ilyazzz wdyt about the docker-compose config at the repo and/or docs?

**Comment by ilyazzz** [comment]
I think `/var/cache/pacoloco` should be mounted as one volume, this was my oversight when I was submitting the docker image. I'll make a PR to update the docs.
