### ISSUE TITLE
pacoloco.go:138: repo archlinux_x86_64 does not exist in config

### ISSUE THREAD

**Issue by Gohub007** [anatol/pacoloco#49]
**we installed on two different boxes the pacoloco service and on both we get the same error:**

```
● pacoloco.service - Pacoloco caching proxy server
     Loaded: loaded (/usr/lib/systemd/system/pacoloco.service; disabled; vendor preset: disabled)
     Active: active (running) since Sun 2022-04-17 07:24:52 CEST; 11min ago
   Main PID: 866 (pacoloco)
      Tasks: 6 (limit: 2350)
     Memory: 14.6M
        CPU: 26ms
     CGroup: /system.slice/pacoloco.service
             └─866 /usr/bin/pacoloco

Apr 17 07:25:46 archvm pacoloco[866]: pacoloco.go:138: repo archlinux_x86_64 does not exist in config
Apr 17 07:28:49 archvm pacoloco[866]: pacoloco.go:138: repo archlinux_x86_64 does not exist in config
Apr 17 07:28:49 archvm pacoloco[866]: pacoloco.go:138: repo archlinux_x86_64 does not exist in config
Apr 17 07:28:49 archvm pacoloco[866]: pacoloco.go:138: repo archlinux_x86_64 does not exist in config
Apr 17 07:32:26 archvm pacoloco[866]: pacoloco.go:138: repo archlinux_x86_64 does not exist in config
```

The clients get error: `The requested URL returned error: 404`
The config file on both server looks the same:

**/etc/pacoloco.yaml**

```yaml
# cache_dir: /var/cache/pacoloco
# port: 9129
download_timeout: 3600 # downloads will timeout if not completed after 3600 sec, 0 to disable timeout
purge_files_after: 2592000 # purge file after 30 days
repos:
  archlinux:
    urls:
      - http://mirror.lty.me/archlinux
      - http://mirrors.kernel.org/archlinux
  archlinux-reflector:
    mirrorlist: /etc/pacman.d/mirrorlist # Be careful! Check that pacoloco URL is NOT included in that file!
  quarry:
    url: http://pkgbuild.com/~anatolik/quarry/x86_64
  sublime:
    url: https://download.sublimetext.com/arch/stable/x86_64
prefetch: # optional section, add it if you want to enable prefetching
  cron: 0 0 3 * * * * # standard cron expression (https://en.wikipedia.org/wiki/Cron#CRON_expression) to define how frequently prefetch, see https://github.com/gorhill/cronexpr#implementation for documentation.
  ttl_unaccessed_in_days: 30  # defaults to 30, set it to a higher value than the number of consecutive days you don't update your systems
  ttl_unupdated_in_days: 300 # defaults to 300, it deletes and stop prefetch packages which hadn't been either updated upstream or requested for ttl_unupdated_in_days.
```

**the clients mirrorlist:**

`Server` = http://archvm.local:9129/repo/archlinux_$arch/$repo/os/$arch

**Comment by anatol** [comment]
That's because the repository name is `archlinux`. Thus correct Server url will be

`Server = http://archvm.local:9129/repo/archlinux/$repo/os/$arch`

**Comment by Gohub007** [comment]
still with adjusted client mirrorlist `http://archvm.local:9129/repo/archlinux/$repo/os/$arch` we get the same 404 error:

`Could not transfer file 'core.db' from archvm.local:9129: The requested URL returned error: 404`
`Could not transfer file 'community.db' from archvm.local:9129: The requested URL returned error: 404`
`Could not transfer file 'extra.db' from archvm.local:9129: The requested URL returned error: 404`
`Warning: too many errors from archvm.local:9129, skipping for the remainder of this transaction`

`● pacoloco.service - Pacoloco caching proxy server
     Loaded: loaded (/usr/lib/systemd/system/pacoloco.service; disabled; vendor preset: disabled)
     Active: active (running) since Sun 2022-04-17 18:15:30 CEST; 10min ago
   Main PID: 1630 (pacoloco)
      Tasks: 5 (limit: 2350)
     Memory: 24.8M
        CPU: 19ms
     CGroup: /system.slice/pacoloco.service
             └─1630 /usr/bin/pacoloco

Apr 17 18:15:30 archvm systemd[1]: Started Pacoloco caching proxy server.
Apr 17 18:15:30 archvm pacoloco[1630]: pacoloco.go:102: Reading config file from /etc/pacoloco.yaml
Apr 17 18:15:30 archvm pacoloco[1630]: prefetch.go:34: The prefetching routine will be run on 2022-04-18 03:00:00.000048433 +0200 CEST m=+31469.913677643
Apr 17 18:15:30 archvm pacoloco[1630]: pacoloco.go:129: Starting server at port 9129
Apr 17 18:16:29 archvm pacoloco[1630]: pacoloco.go:138: repo archlinux does not exist in config
Apr 17 18:16:29 archvm pacoloco[1630]: pacoloco.go:138: repo archlinux does not exist in config
Apr 17 18:16:29 archvm pacoloco[1630]: pacoloco.go:138: repo archlinux does not exist in config
`

**Comment by Gohub007** [comment]
fixed it:
pacoloco could not create directory: `/var/cache/pacoloco/pkgs/archlinux` **no permission**
then:
copy the all *.db to `/var/cache/pacoloco/pkgs/archlinux`
now it works
