### ISSUE TITLE
Publishing to ghcr.io

### ISSUE THREAD

**Issue by zhulik** [anatol/pacoloco#59]
Hello, 

I was looking for a shared pacman cache for my computers and found pacoloco. I looks exactly like what I need, the only problem is that my NAS running kubernetes which means I need pacoloco to be published in a registry.

What do you say if I open a PR with a github workflow that runs tests and then builds and publishes the image to ghcr.io so that anyone can simply pull the image from there?

The logic is simple: every time you push to `master` it will publish to `latest`, every time you create a release, it will publish a corresponding tag.

Thank you!

**Comment by anatol** [comment]
It sounds like a great idea. I am all for making NAS users life easier.

**Comment by anatol** [comment]
cc @ilya-zlobintsev

**Comment by ilya-zlobintsev** [comment]
Sounds good to me. README should also be updated to mention ghcr after it's implemented.

**Comment by HarHarLinks** [comment]
This is now done.
