### ISSUE TITLE
Question: Remove some packages from prefetching manually

### ISSUE THREAD

**Issue by gary094** [anatol/pacoloco#80]
Hello!

I'd like to remove some packages manually by hand because I do no longer need them prefetched, so these packages do not take unnecessary space.

I know that `ttl_unaccessed_in_days`  and `ttl_unupdated_in_days` exists, however I do not want to change this globally for each package but only for a few selected ones and just one time only.

Would the following be a viable workflow?

- `delete from packages where package_name = "package";`
- remove package from package cache at `/cache/pkgs/archlinux`:  `rm package.pkg.tar.zst` and `rm package.pkg.tar.zst.sig`

**Comment by Focshole** [comment]
The first option should disable that package from being prefetched in the future, while the second option should simply delete the existing cached package. So, you should probably do both!

**Comment by gary094** [comment]
Yes sure it was meant to be done like first step delete from database then second step remove package and signature

alright, thanks then I'll try that

**Comment by Focshole** [comment]
> alright, thanks then I'll try that

No problem, did it work?

**Comment by gary094** [comment]
> No problem, did it work?

Well I need to wait until this package gets updated upstream, then I know for sure whether manual removal worked. So far the last few days it has not been prefetched, which is good.
