### ISSUE TITLE
pacoloco.yaml confusing

### ISSUE THREAD

**Issue by Cody-Learner** [anatol/pacoloco#82]
This is overall nice program that works well for me. Thank you for providing it.

However, I'd like to add that I found the configuration confusing even after reading the documentation:  https://github.com/anatol/pacoloco#readme

Under the 'repos:' section, how would I add my local AUR repo, as both a URL and file?

Under the 'archlinux-reflector:' section, I was somewhat confused because I use the reflector package and initially thought it was related to setting it up. Possibly using a term other than reflector here would be better? 

Seems if I point a web browser to the pacoloco URL, http://192.168.2.139:9129/repo/archlinux/extra/os/x86_64, it shows the extra packages.  Then if point a browser to the pacoloco URL, http://192.168.2.139:9129/repo/archlinux/core/os/x86_64, it shows the extra packages rather than core. If I delete the x86_64 html file from the pacoloco cache, the x86_64 html file will be regenerated for which ever repo is searched in a browser the first time, then seems to not be updated?

Could this be caused by something incorrectly set in my pacoloco.yaml configuration? The issue with the web browser is not a big deal because it seems to have no effect on pacoloco, but I did find it confusing while trying to set it up.

It would seem providing a bare minimal working config for a default configured Arch install (ie: core and extra repos enabled) would make things a bit less confusing, along with a man page for all the config file settings/options.

**Comment by anatol** [comment]
There was a similar request to make the default config simple. https://github.com/anatol/pacoloco/issues/81
