### ISSUE TITLE
Commit 567e1ce breaks arm build

### ISSUE THREAD

**Issue by Humandoodlebug** [anatol/pacoloco#9]
Commit 567e1cea1dbfc7c9e59224159918f4e607c3bf41 seems to break the build on ARM devices (including native and cross-compilation).

Building on master (99d64f3532c55609bd2d4f7c54dc2060eb0411a1) gives:

```
./purge.go:43:31: cannot use atimeUnix.Sec (type int32) as type int64 in argument to time.Unix
./purge.go:43:46: cannot use atimeUnix.Nsec (type int32) as type int64 in argument to time.Unix
```

Last working commit: 8c7b8d97be811d85a0a6f52d193a19d465116905

This was tested on a Raspberry Pi 4 (armv7).

**Comment by anatol** [comment]
What is the best way to reproduce this compilation issue at x86 architecture?

**Comment by Humandoodlebug** [comment]
This should do it in bash:
`GOARCH=arm GOARM=7 go build`

**Comment by anatol** [comment]
Could you please check if https://github.com/anatol/pacoloco/commit/6c462e666b83f62c8f3ac426b2a9b92192533d5d works for you?

And while we are here what is the best way to run `go test` for ARM architecture? If I run `GOARCH go test` it fails for me:

```
GOARCH=arm GOARM=7 go test 
fork/exec /tmp/go-build348346871/b001/pacoloco.test: exec format error
FAIL	github.com/anatol/pacoloco	0.001s
```

**Comment by Humandoodlebug** [comment]
That works perfectly, and tests pass:
```
go: downloading github.com/google/go-cmp v0.4.0
PASS
ok      github.com/anatol/pacoloco      0.039s
```

Thanks for getting back so quick.
